// LoggingObserverDriver.h

#ifndef COMP345WARZONE_LOGGINGOBSERVERDRIVER_H
#define COMP345WARZONE_LOGGINGOBSERVERDRIVER_H

void testLoggingObserver();

#endif //COMP345WARZONE_LOGGINGOBSERVERDRIVER_H
